// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// accCpp
List accCpp(IntegerMatrix AM, CharacterVector nodeNames, CharacterVector index);
RcppExport SEXP ToPASeq_accCpp(SEXP AMSEXP, SEXP nodeNamesSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type AM(AMSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type nodeNames(nodeNamesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type index(indexSEXP);
    __result = Rcpp::wrap(accCpp(AM, nodeNames, index));
    return __result;
END_RCPP
}
// colMax
NumericVector colMax(NumericMatrix X);
RcppExport SEXP ToPASeq_colMax(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    __result = Rcpp::wrap(colMax(X));
    return __result;
END_RCPP
}
// colMin
NumericVector colMin(NumericMatrix X);
RcppExport SEXP ToPASeq_colMin(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    __result = Rcpp::wrap(colMin(X));
    return __result;
END_RCPP
}
// downstreamCpp
IntegerVector downstreamCpp(IntegerMatrix AM, CharacterVector nodeNames, CharacterVector index);
RcppExport SEXP ToPASeq_downstreamCpp(SEXP AMSEXP, SEXP nodeNamesSEXP, SEXP indexSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerMatrix >::type AM(AMSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type nodeNames(nodeNamesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type index(indexSEXP);
    __result = Rcpp::wrap(downstreamCpp(AM, nodeNames, index));
    return __result;
END_RCPP
}
