# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

accCpp <- function(AM, nodeNames, index) {
    .Call('ToPASeq_accCpp', PACKAGE = 'ToPASeq', AM, nodeNames, index)
}

colMax <- function(X) {
    .Call('ToPASeq_colMax', PACKAGE = 'ToPASeq', X)
}

colMin <- function(X) {
    .Call('ToPASeq_colMin', PACKAGE = 'ToPASeq', X)
}

downstreamCpp <- function(AM, nodeNames, index) {
    .Call('ToPASeq_downstreamCpp', PACKAGE = 'ToPASeq', AM, nodeNames, index)
}

